### ISSUE TITLE
Recherche du livre de recette ne retourne aucun résultats

### ISSUE THREAD

**Issue by Daluzeau-B** [Leiriad/-Neoforge-1.20.1-Inventorium#1]
Dans le livre de recette, que ce soit celui dans l'inventaire du personnage ou de l'établi la recherche ne retourne aucun résultat.
J'ai essayé des mots en français/anglais, de simple lettres, des mots entier, minuscule majuscule, mot exacte.

![image](https://github.com/user-attachments/assets/f4a66c9a-063a-41ce-a2ef-ed2f1fede950)

![image](https://github.com/user-attachments/assets/fb38e0cd-bc06-4cf3-8390-acec56f01eac)

**Comment by Leiriad** [comment]
J'ai updaté le mod de performance Modern Fix. C'est lui qui interférait avec le mod d'annuaire de recettes Roughly Enough Items et qui causait ce bug. Tu peux retrouver le commit ici : [I updated Modern fix: modernfix-forge-5.15.0 was interfering with Roughly Enough Items causing the search to break in the vanilla recipe book.](https://github.com/Leiriad/-Neoforge-1.20.1-Inventorium/commit/50c693f75e36430c5e7b355a10a11496d7e282ea)
